<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>13</LangVersion>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <PackageId>Randhomme.TPToolkitLib</PackageId>
    <Title>$(AssemblyName)</Title>
    <Authors>Randhomme</Authors>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="WorldObject\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Pfim" Version="0.11.4" />
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.6" />
    <PackageReference Include="StbImageWriteSharp" Version="1.16.7" />
  </ItemGroup>

</Project>
